In [9]:
import numpy as np
import random
from collections import deque, defaultdict
import networkx as nx
import matplotlib.pyplot as plt

In [10]:
# Generate a symmetrical random distance matrix for 15 nodes
np.random.seed(123)
num_nodes = 15
upper_triangular = np.triu(np.random.randint(1, 10, size=(num_nodes, num_nodes)), 1)
distance_matrix = upper_triangular + upper_triangular.T

In [11]:
# Define the tree structure
tree = defaultdict(list)
root = 1

In [12]:
# Level 2 nodes
tree[root] = [2, 3, 4, 5]

# Level 3 nodes
tree[2] = [6]
tree[3] = [7, 8]
tree[4] = [9]
tree[5] = [10]

# Level 4 nodes
tree[6] = [11]
tree[7] = [12]
tree[8] = [13]
tree[9] = [14]
tree[10] = [15]

In [13]:
# Flatten the tree into a BFS path
def bfs_full_path(tree, start_node):
    visited = set()
    queue = deque([start_node])
    path = []
    
    while queue:
        current_node = queue.popleft()
        if current_node not in visited:
            visited.add(current_node)
            path.append(current_node)
            for neighbor in tree[current_node]:
                if neighbor not in visited:
                    queue.append(neighbor)
    return path

In [14]:
# Find a path through the tree with BFS that visits all nodes
path = bfs_full_path(tree, root)

In [15]:
# Print the results
print("Symmetrical Distance Matrix:")
print(distance_matrix)
print("\nTree Structure:")
for node in tree:
    print(f"Node {node}: {tree[node]}")
print("\nBFS Path through all nodes:")
print(path)

Symmetrical Distance Matrix:
[[0 3 7 2 4 7 2 1 2 1 1 4 5 1 1]
 [3 0 8 4 3 5 8 3 5 9 1 8 4 5 7]
 [7 8 0 3 2 9 4 6 1 3 7 3 5 5 7]
 [2 4 3 0 8 7 8 2 6 8 3 5 9 2 3]
 [4 3 2 8 0 9 2 7 4 4 6 8 3 4 4]
 [7 5 9 7 9 0 7 7 7 2 4 5 4 2 1]
 [2 8 4 8 2 7 0 2 4 5 8 7 2 5 4]
 [1 3 6 2 7 7 2 0 1 1 9 9 5 9 7]
 [2 5 1 6 4 7 4 1 0 8 2 4 2 9 8]
 [1 9 3 8 4 2 5 1 8 0 2 4 9 4 8]
 [1 1 7 3 6 4 8 9 2 2 0 1 9 3 6]
 [4 8 3 5 8 5 7 9 4 4 1 0 8 6 2]
 [5 4 5 9 3 4 2 5 2 9 9 8 0 3 7]
 [1 5 5 2 4 2 5 9 9 4 3 6 3 0 8]
 [1 7 7 3 4 1 4 7 8 8 6 2 7 8 0]]

Tree Structure:
Node 1: [2, 3, 4, 5]
Node 2: [6]
Node 3: [7, 8]
Node 4: [9]
Node 5: [10]
Node 6: [11]
Node 7: [12]
Node 8: [13]
Node 9: [14]
Node 10: [15]
Node 11: []
Node 12: []
Node 13: []
Node 14: []
Node 15: []

BFS Path through all nodes:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [16]:
# Calculate the total distance of the path
if path:
    total_distance = sum(distance_matrix[path[i]-1][path[i + 1]-1] for i in range(len(path) - 1))
    print("\nTotal Distance of the Path:")
    print(total_distance)
else:
    print("\nNo path found.")



Total Distance of the Path:
71
